import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthSubscriber from "components/Auth/AuthSubscriber";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                data-theme="dark"
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-base-300 min-h-screen overflow-x-hidden`}
            >
                <AuthSubscriber /> {children}
            </body>
        </html>
    );
}
